<a href="https://colab.research.google.com/github/lisajl/DigitalHistory/blob/master/Digital_History/Week3-Introduction-to-Open-Data-Importing-Data-and-Basic-Data-Wrangling/Homework/Week3-Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <div align = "center">Homework 2</div>
# <div align = "center">US Census Data</div>

**Welcome to Homework 2!** In this homework you will be using techniques you learned in Working with Data using Pandas. The purpose of this homework is for you to try data manipulation with ```Pandas``` and to express your observations. 

Feel free to refer back to week 4 tutorial notebook and ask questions on Piazza!

### Grading

There are a total of ten questions and each question is worth 1 point.

In order to work on the Homework sections and submit them for grading, you'll need to run the code block below. It will ask for your student ID number and then create a folder that will house your answers for each question. At the very end of the notebook, there is a code section that will download this folder as a zip file to your computer. This zip file will be your final submission.

In [ ]:
import os
import shutil

!rm -rf sample_data

student_id = input('Please Enter your Student ID: ') # Enter Student ID.

while len(student_id) != 9:
 student_id = int('Please Enter your Student ID: ')  
  
folder_location = f'{student_id}/Week_Four/Homework'
if not os.path.exists(folder_location):
  os.makedirs(folder_location)
  print('Successfully Created Directory, Lets get started')
else:
  print('Directory Already Exists')

### Import Library

In [1]:
import pandas as pd

### Load dataset

In [2]:
url = 'https://raw.githubusercontent.com/bitprj/BitUniversity/master/Digital_History/Week3-Introduction-to-Open-Data-Importing-Data-and-Basic-Data-Wrangling/data/acs2017_county_data.csv'
df = pd.read_csv(url)
df

      CountyId        State  ... FamilyWork  Unemployment
0         1001      Alabama  ...        0.1           5.2
1         1003      Alabama  ...        0.1           5.5
2         1005      Alabama  ...        0.3          12.4
3         1007      Alabama  ...        0.3           8.2
4         1009      Alabama  ...        0.1           4.9
...        ...          ...  ...        ...           ...
3215     72145  Puerto Rico  ...        0.2          16.8
3216     72147  Puerto Rico  ...        0.0          12.8
3217     72149  Puerto Rico  ...        0.2          24.8
3218     72151  Puerto Rico  ...        0.0          25.4
3219     72153  Puerto Rico  ...        0.0          24.0

[3220 rows x 37 columns]

## Homework Questions

**Since this dataset has lots of information, feel free to select a set of columns to answer each question.**

In [3]:
df.head()

   CountyId    State          County  ...  SelfEmployed  FamilyWork  Unemployment
0      1001  Alabama  Autauga County  ...           5.6         0.1           5.2
1      1003  Alabama  Baldwin County  ...           6.3         0.1           5.5
2      1005  Alabama  Barbour County  ...           6.5         0.3          12.4
3      1007  Alabama     Bibb County  ...           6.3         0.3           8.2
4      1009  Alabama   Blount County  ...           4.0         0.1           4.9

[5 rows x 37 columns]

### Q1. List out all column names of ```df```. (1 pt)

#### Code:

In [6]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/1.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT CODE BELOW
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3220 entries, 0 to 3219
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CountyId          3220 non-null   int64
 1   State             3220 non-null   object
 2   County            3220 non-null   object
 3   TotalPop          3220 non-null   int64
 4   Men               3220 non-null   int64
 5   Women             3220 non-null   int64
 6   Hispanic          3220 non-null   float64
 7   White             3220 non-null   float64
 8   Black             3220 non-null   float64
 9   Native            3220 non-null   float64
 10  Asian             3220 non-null   float64
 11  Pacific           3220 non-null   float64
 12  VotingAgeCitizen  3220 non-null   int64
 13  Income            3220 non-null   int64
 14  IncomeErr         3220 non-null   int64
 15  IncomePerCap      3220 non-null   int64
 16  IncomePerCapErr   3220 non-null   int64
 17  Poverty           3220 non-null   float64
 18  ChildPoverty      3219 non-null   float64
 19  Professional      3220 non-null   float64
 20  Service           3220 non-null   float64
 21  Office            3220 non-null   float64
 22  Construction      3220 non-null   float64
 23  Production        3220 non-null   float64
 24  Drive             3220 non-null   float64
 25  Carpool           3220 non-null   float64
 26  Transit           3220 non-null   float64
 27  Walk              3220 non-null   float64
 28  OtherTransp       3220 non-null   float64
 29  WorkAtHome        3220 non-null   float64
 30  MeanCommute       3220 non-null   float64
 31  Employed          3220 non-null   int64
 32  PrivateWork       3220 non-null   float64
 33  PublicWork        3220 non-null   float64
 34  SelfEmployed      3220 non-null   float64
 35  FamilyWork        3220 non-null   float64
 36  Unemployment      3220 non-null   float64
dtypes: float64(25), int64(10), object(2)
memory usage: 930.9+ KB

### Q2. Set ```CountyId``` as an index for ```df```. (1 pt)

Hint: Use ```set_index```.

#### Answer:

In [9]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/2.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT CODE BELOW
df.set_index(keys='CountyId',inplace=True)

KeyError: ignored

### Q3 (a) Find the rows where ```Unemployment``` is greater than 10. (0.5 pt)

Hint: Use ```df.loc[]```.

#### Code:

In [10]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/3.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT CODE BELOW
df.loc[df['Unemployment'] > 10]

                State               County  ...  FamilyWork  Unemployment
CountyId                                    ...
1005          Alabama       Barbour County  ...         0.3          12.4
1011          Alabama       Bullock County  ...         0.0          12.1
1015          Alabama       Calhoun County  ...         0.1          10.1
1025          Alabama        Clarke County  ...         0.0          15.2
1035          Alabama       Conecuh County  ...         1.0          14.5
...               ...                  ...  ...         ...           ...
72145     Puerto Rico  Vega Baja Municipio  ...         0.2          16.8
72147     Puerto Rico    Vieques Municipio  ...         0.0          12.8
72149     Puerto Rico   Villalba Municipio  ...         0.2          24.8
72151     Puerto Rico    Yabucoa Municipio  ...         0.0          25.4
72153     Puerto Rico      Yauco Municipio  ...         0.0          24.0

[346 rows x 36 columns]

### Q3 (b) How many counties have ```Unemployment``` > 10? Type your answer in the Answer section. (0.5 pt)

Hint: Look at how many rows Q3 (a) displays.

#### Answer:

In [11]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/3.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW
#346

### Q4. Find the state with most self-employeed population. (1 pt)

Hint: Refer to 9.0 Now Try This in week 4 material.

#### Code:

In [14]:
# INSERT CODE BELOW
# This is not part of grading.
df.groupby(['State'])['SelfEmployed'].sum().sort_values(ascending = False)

State
Texas                   2268.2
Nebraska                1213.6
Kansas                  1075.8
Georgia                  972.5
Missouri                 959.7
South Dakota             918.1
Iowa                     890.7
North Dakota             789.0
Kentucky                 781.6
Tennessee                759.7
Virginia                 740.3
Montana                  738.4
Minnesota                702.6
North Carolina           669.7
Illinois                 667.0
Puerto Rico              652.2
Colorado                 639.0
Oklahoma                 619.6
California               554.9
Arkansas                 553.2
Michigan                 536.6
Wisconsin                511.6
Indiana                  486.2
Ohio                     486.1
Mississippi              475.7
Florida                  422.0
Pennsylvania             402.3
New York                 402.1
Idaho                    386.5
Alabama                  373.4
Louisiana                357.3
Oregon                   332.6
Washington               299.2
West Virginia            267.1
South Carolina           248.8
New Mexico               237.3
Alaska                   209.4
Wyoming                  179.3
Utah                     172.4
Maine                    162.4
Vermont                  138.9
Maryland                 136.0
Nevada                   120.1
Massachusetts            116.8
New Jersey                99.8
Arizona                   89.3
New Hampshire             77.1
Connecticut               50.0
Hawaii                    37.7
Rhode Island              31.1
Delaware                  13.0
District of Columbia       4.3
Name: SelfEmployed, dtype: float64

#### Answer: type your answer in a string form.

In [16]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/4.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW
'Texas'

'Texas'

### Q5 (a) Select the state with most self-employed population and save the dataframe as ```df_self_emp```. (0.5 pt)

Hint: Use ```df.loc[]``` and select the rows where ```State``` is the one you found in Q4.

#### Code:

In [25]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/5.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT CODE BELOW
df_self_emp = df.loc[df['State']=='Texas']
df_self_emp

          State           County  ...  FamilyWork  Unemployment
CountyId                          ...
48001     Texas  Anderson County  ...         0.2           4.3
48003     Texas   Andrews County  ...         0.3           4.5
48005     Texas  Angelina County  ...         0.1           7.6
48007     Texas   Aransas County  ...         0.2           6.7
48009     Texas    Archer County  ...         0.0           3.0
...         ...              ...  ...         ...           ...
48499     Texas      Wood County  ...         0.4           7.8
48501     Texas    Yoakum County  ...         0.1           7.5
48503     Texas     Young County  ...         1.2           4.5
48505     Texas    Zapata County  ...         0.4          12.4
48507     Texas    Zavala County  ...         0.1          10.1

[254 rows x 36 columns]

### Q5 (b) Find the top 2 most popular means of transportation to work in ```df_self_emp```. (0.5 pt)

Hint: Use the following columns: 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp', 'WorkAtHome' and an AGGREGATE function.

#### Code:

In [21]:
# INSERT CODE BELOW
# This is not part of grading.
df_self_emp[['Drive','Carpool','Transit','Walk','OtherTransp','WorkAtHome']].sum()

Drive          20455.0
Carpool         2888.5
Transit           79.4
Walk             600.6
OtherTransp      363.2
WorkAtHome      1013.9
dtype: float64

#### Answer: type your answer in a string form.

In [22]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/5.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW
'Drive, Carpool'

'Drive, Carpool'

### Q6. What are the top 3 states with highest ```mean commute```? (1 pt)

Hint: This one is similar to Q4.

#### Code:

In [23]:
# INSERT CODE BELOW
# This is not part of grading.
df.groupby(['State'])['MeanCommute'].sum().sort_values(ascending = False)

State
Texas                   5825.3
Georgia                 4119.7
Virginia                3676.2
Kentucky                3048.9
Missouri                2721.9
Tennessee               2519.0
North Carolina          2518.8
Illinois                2402.2
Indiana                 2241.1
Puerto Rico             2207.0
Ohio                    2153.8
Mississippi             2151.6
Iowa                    1936.4
Michigan                1918.0
Minnesota               1860.6
Kansas                  1860.4
Florida                 1768.2
Alabama                 1754.7
Arkansas                1726.0
Pennsylvania            1701.8
Louisiana               1697.7
Nebraska                1681.4
Oklahoma                1678.1
Wisconsin               1608.7
New York                1594.5
West Virginia           1546.6
California              1480.6
Colorado                1386.6
South Carolina          1198.8
South Dakota            1119.8
Montana                  981.5
North Dakota             970.9
Idaho                    947.4
Washington               904.4
Maryland                 734.3
Oregon                   726.5
New Mexico               665.6
New Jersey               641.2
Utah                     582.8
Wyoming                  441.5
Maine                    376.0
Nevada                   369.5
Massachusetts            354.4
Vermont                  339.6
Arizona                  325.5
Alaska                   324.8
New Hampshire            254.0
Connecticut              207.8
Rhode Island             124.0
Hawaii                   104.6
Delaware                  77.3
District of Columbia      30.0
Name: MeanCommute, dtype: float64

#### Answer: type your answer in a string form.

In [24]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/6.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW

"Texas, Georgia, and Virginia"

'Texas, Georgia, and Virginia'

### Q7 (a) Select the subset of data where ```State``` is one of the states we found in question 6 and save it as ```top_three```. (.33 point)

Hint: Use ```df['State'].isin()```. You may refer to the practical exercise section in Week 4 material.

#### Code:

In [28]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/7.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT CODE BELOW

top_three = df.loc[df['State'].isin(['Texas','Georgia','Virginia'])]
top_three

             State               County  ...  FamilyWork  Unemployment
CountyId                                 ...
13001      Georgia       Appling County  ...         0.2           7.7
13003      Georgia      Atkinson County  ...         0.0           8.4
13005      Georgia         Bacon County  ...         0.0           3.1
13007      Georgia         Baker County  ...         0.0           2.5
13009      Georgia       Baldwin County  ...         0.0           9.0
...            ...                  ...  ...         ...           ...
51800     Virginia         Suffolk city  ...         0.2           6.7
51810     Virginia  Virginia Beach city  ...         0.2           5.3
51820     Virginia      Waynesboro city  ...         0.1           4.4
51830     Virginia    Williamsburg city  ...         0.0           7.3
51840     Virginia      Winchester city  ...         0.4           4.3

[546 rows x 36 columns]

### Q7 (b) How many counties are there in the top three states? (.33 pt)

Hint: Use one of the aggregate functions. (```sum()```, ```mean()```, or ```count()```)

#### Code:

In [29]:
# INSERT CODE BELOW
# This is not part of grading.
top_three['County'].count()

546

#### Answer: type your answer in a string form.

In [ ]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/7.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW
'546'

### Q7 (c) Find the County with the most ```MeanCommute``` time in ```top_three``` (.34 pt).

Hint: Use ```sort_values(by= )```.

#### Code:

In [30]:
# INSERT CODE BELOW
# This is not part of grading.
top_three.sort_values(by='MeanCommute')

             State               County  ...  FamilyWork  Unemployment
CountyId                                 ...
48263        Texas          Kent County  ...         1.0           1.6
48023        Texas        Baylor County  ...         0.0           2.3
48487        Texas     Wilbarger County  ...         0.4           5.8
48205        Texas       Hartley County  ...         2.0           1.2
48269        Texas          King County  ...         0.0           6.0
...            ...                  ...  ...         ...           ...
51049     Virginia    Cumberland County  ...         0.0           7.0
51187     Virginia        Warren County  ...         0.2           6.0
51179     Virginia      Stafford County  ...         0.1           4.3
48407        Texas   San Jacinto County  ...         0.1           6.5
51193     Virginia  Westmoreland County  ...         0.2           7.3

[546 rows x 36 columns]

#### Answer: type your answer in a string form.

In [31]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/7.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW

'Westmoreland County, VA'

'Westmoreland County, VA'

### Q8. Find the top 5 states with highest income level and find out their top professional working field: 'Professional', 'Service', 'Office', 'Construction', or 'Production.' 

Hint: This question is a combination of Q6 and Q7. You may add more blocks to write codes and use the same approach as in Q6 and Q7.

#### Code:

In [35]:
# INSERT CODE BELOW
# This is not part of grading.
#df.groupby(['State'])['MeanCommute'].sum().sort_values(ascending = False)
#top_three.sort_values(by='MeanCommute')
#top_three = df.loc[df['State'].isin(['Texas','Georgia','Virginia'])]
#top_three
#df.groupby(['State'])['Income'].sum().sort_values(ascending = False)
top_five_income = df.loc[df['State'].isin(['Texas','Virginia','Georgia','Illinois','Iowa'])]
top_five_income[['Professional','Service','Office','Construction','Production']].sum()

Professional    22994.0
Service         13431.9
Office          16506.8
Construction     9718.9
Production      12050.7
dtype: float64

#### What are the top five states with highest income? Type your answer in a string form. (0.5 pts)

In [36]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/8.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW.

'Texas, Virginia, Georgia, Illinois, Iowa'

'Texas, Virginia, Georgia, Illinois, Iowa'

#### What is the most popular working field in the top five states? Type your answer in a string form. (0.5 pts)

In [37]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/8.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW.
'Professional'

'Professional'

### Q9. Find the state with highest male population. (1 pt)

Hint: This is similar to Q4.

#### Code:

In [40]:
# INSERT CODE BELOW
# This is not part of grading.
df.groupby(['State'])['Men'].sum().sort_values(ascending = False)

State
California              19366579
Texas                   13616977
Florida                  9914361
New York                 9604111
Illinois                 6312600
Pennsylvania             6260160
Ohio                     5686081
Georgia                  4968887
North Carolina           4895368
Michigan                 4880579
New Jersey               4372321
Virginia                 4113988
Washington               3580888
Arizona                  3385055
Massachusetts            3293426
Indiana                  3258279
Tennessee                3217073
Missouri                 2981332
Maryland                 2906277
Wisconsin                2864115
Minnesota                2731831
Colorado                 2731315
South Carolina           2376759
Alabama                  2350806
Louisiana                2281239
Kentucky                 2179025
Oregon                   1993822
Oklahoma                 1930615
Connecticut              1754046
Puerto Rico              1653997
Iowa                     1548035
Utah                     1506614
Arkansas                 1461651
Nevada                   1450091
Mississippi              1448717
Kansas                   1445980
New Mexico               1032086
Nebraska                  943547
West Virginia             907621
Idaho                     830627
Hawaii                    713981
New Hampshire             659131
Maine                     651040
Montana                   517860
Rhode Island              512581
Delaware                  456876
South Dakota              430587
Alaska                    386319
North Dakota              382121
District of Columbia      319046
Vermont                   308026
Wyoming                   298301
Name: Men, dtype: int64

#### Answer: type your answer in a string form.

In [41]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/9.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW
'California'

'California'

### Q10. Find the state where male population is greater than female population. (1pt)
Hint 1: Find the sum of male and female population at a state level - Use ```groupby``` and save this dataframe as ```total_pop```.

Hint 2: Using ```total_pop.loc[criteria]```, find out the states with a greater male population.

Hint 3: There are 10 states that meet this condition.

#### Code:

In [44]:
# INSERT CODE BELOW
# This is not part of grading.
total_pop = df.groupby(['State'])['Men','Women'].sum()
total_pop.loc[total_pop['Men'] > total_pop['Women']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  This is separate from the ipykernel package so we can avoid doing imports until

                  Men    Women
State
Alaska         386319   352246
Colorado      2731315  2705204
Hawaii         713981   707677
Idaho          830627   826748
Montana        517860   512002
Nevada        1450091  1437634
North Dakota   382121   363354
South Dakota   430587   424857
Utah          1506614  1487327
Wyoming        298301   284899

#### Answer: type your answer in a string form.

In [45]:
# Once your have verified your answer please uncomment the line below and run it, this will save your code 
#%%writefile -a {folder_location}/10.py
# Please note that if you uncomment and run multiple times, the program will keep appending to the file.

# INSERT YOUR ANSWER BELOW
'Alaska, Colorado, Hawaii, Idaho, Montana, Nevada, North Dakota, South Dakota, Utah, Wyoming'

'Alaska, Colorado, Hawaii, Idaho, Montana, Nevada, North Dakota, South Dakota, Utah, Wyoming'


## Submission
Run this code block to download your answers.

In [ ]:
from google.colab import files
!zip -r "{student_id}.zip" "{student_id}"
files.download(f"{student_id}.zip")